name: Main

on: [push]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PG_CONNECTION_STRING: postgres://postgres:password@localhost:5432
      PG_DB: postgres
      UPSTASH_URL: http://srh:8080
      UPSTASH_TOKEN: example_token

    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      redis:
        image: redis/redis-stack-server:6.2.6-v6
      srh:
        image: hiett/serverless-redis-http:latest
        env:
          SRH_MODE: env
          SRH_TOKEN: example_token
          SRH_CONNECTION_STRING: redis://redis:6379

    steps:
      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql user: postgres
          postgresql password: password

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check types
        run: yarn type-check

      - name: Check linting
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Build storybook
        run: yarn build-storybook

      - name: Build package
        run: yarn build

      # - name: Setup examples
      #   run: |
      #     cd examples/next-invite-example
      #     yarn install --frozen-lockfile
      #     yarn link next-invite
      #     yarn build

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5
